name: Benchmark

on:
  workflow_dispatch:

jobs:

  benchmark:

    name: Benchmark
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - run: pip install -r requirements.txt

    - name: Save Action Info
      run: |
        touch out/note.txt
        echo '```' >> out/note.txt
        echo ${{ github.ref }}
        echo ${{ github.ref }} >> out/note.txt
        echo ${{ github.run_id }}
        echo ${{ github.run_id }} >> out/note.txt
        echo ${{ github.sha }}
        echo ${{ github.sha }} >> out/note.txt
    
    - name: Save System Info (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        cat /proc/cpuinfo
        cat /proc/cpuinfo >> out/note.txt
        cat /proc/meminfo
        cat /proc/meminfo >> out/note.txt
    
    - name: Save System Info (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        systeminfo
        systeminfo >> out/note.txt

    - name: Save System Info (MacOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        system_profiler SPHardwareDataType
        system_profiler SPHardwareDataType >> out/note.txt
    
    - name: Save Python and Fracdiff versions
      run: |
        python --version
        python --version >> out/note.txt
        pip show fracdiff
        pip show fracdiff >> out/note.txt
        echo '```' >> out/note.txt

    - name: Time
      run: python time.py

    - name: Plot
      run: python plot.py

    - name: Upload Outputs
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: out

    - name: Release
      # uses: softprops/action-gh-release@v1
      # https://github.com/softprops/action-gh-release/issues/139
      uses: softprops/action-gh-release@59c3b4891632ff9a897f99a91d7bc557467a3a22
      with:
        name: ${{ github.run_id }}-${{ matrix.os }}
        tag_name: ${{ github.run_id }}
        body_path: out/note.txt
        files: ./out/*
